export { default as VueAdvancedChat } from './lib/ChatWindow.vue'
export type {
	AutoScroll,
	CustomAction,
	Events,
	LastMessage,
	LinkOptions,
	Message,
	MessageAction,
	MessageFile,
	MessageReactions,
	Props,
	Room,
	RoomUser,
	StringNumber,
	TemplateText,
	TextFormatting,
	TextMessages,
	ThemeStyles,
	UsernameOptions,
	UserStatus,
} from './types'
